## Recuperar todas las peliculas
GET  http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

###   Recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=action

### crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
      "Crime",
      "Drama"
    ]
    
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

Content-Type: application/json
{
  "year": 1994
}